name: Test case report
description: Create a test case report
title: "[Test Case] "
labels: ["test-case"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Test Case Report
        Please fill out the following form to report a test case.

  # contact
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: In case we won't be able to contact you on GitHub, please provide us with an email address or other contact details.
      placeholder: ex. email@example.com
    validations:
      required: false

  # priority
  - type: dropdown
    id: priority
    attributes:
      label: Priority of this this bug
      multiple: false
      options:
        - Low
        - Medium
        - High

  # description
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the test case you want to report.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  # expected result
  - type: textarea
    id: expected-result
    attributes:
      label: Expected Result
      description: Please describe the expected result of the test case.
      placeholder: Tell us what you see!
    validations:
      required: true

  # actual result
  - type: textarea
    id: actual-result
    attributes:
      label: Actual Result
      description: Please describe the actual result of the test case.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  # steps to reproduce
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please describe the steps to reproduce the test case.
      placeholder: Tell us what you see!
    validations:
      required: true

  # checkboxes if test passed|failed|not executed
  - type: checkboxes
    id: test-status
    attributes:
      label: Test Status
      description: Please select the status of the test case.
      options:
        - label: Passed
          required: false
        - label: Failed
          required: false
        - label: Not executed
          required: false

  # attachments
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: Please attach any relevant files. Screenshots, videos, logs, etc.
      placeholder: Drag and drop files here or click to upload.
    validations:
      required: false



  - type: markdown
    attributes:
      value: |
        # OLD DOWN THERE 🥰 ⬇️⬇️⬇️⬇️⬇️⬇️⬇️💀☠️👻👻👻👻👽👽🎉🌠🌠

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
