name: Test case report
description: Create a test case report
title: "[Test Case] "
labels: ["test-case"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Test Case Report
        Please fill out the following form to report a test case.

  # contact
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: In case we won't be able to contact you on GitHub, please provide us with an email address or other contact details.
      placeholder: ex. email@example.com
    validations:
      required: false

  # priority
  - type: dropdown
    id: priority
    attributes:
      label: Priority of this this bug
      multiple: false
      options:
        - Low
        - Medium
        - High

  # description
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the test case you want to report.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  # expected result
  - type: textarea
    id: expected-result
    attributes:
      label: Expected Result
      description: Please describe the expected result of the test case.
      placeholder: Tell us what you see!
    validations:
      required: true

  # actual result
  - type: textarea
    id: actual-result
    attributes:
      label: Actual Result
      description: Please describe the actual result of the test case.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  # steps to reproduce
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please describe the steps to reproduce the test case.
      placeholder: Tell us what you see!
    validations:
      required: true

  # checkboxes if test passed|failed|not executed
  - type: checkboxes
    id: test-status
    attributes:
      label: Test Status
      description: Please select the status of the test case.
      options:
        - label: Passed
          required: false
        - label: Failed
          required: false
        - label: Not executed
          required: false

  # attachments
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: Please attach any relevant files. Screenshots, videos, logs, etc.
      placeholder: Drag and drop files here or click to upload.
    validations:
      required: false